services:
  oltdatacom-backup:
    build: .
    container_name: oltdatacom-backup
    restart: unless-stopped
    env_file:
      - .env
    # Se quiser ver os logs no host:
    volumes:
      - /home/oltdatacom/backups:/app/backups
      - /home/oltdatacom/logs:/var/log

