services:
  olt-backup:
    build: .
    container_name: olt-backup-datacom
    network_mode: "host"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/home/oltdatacom/logs
      - ./backups:/home/oltdatacom/backups
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Bahia
